services:
  db:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: abdulrahman
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

networks:
  db:
    driver: bridge

volumes:
  db:
  minio_data:
    driver: local